import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod/legacy.dart';

enum AppLanguage {
  zh,
  en,
}

final languageProvider = StateProvider<AppLanguage>((ref) {
  return AppLanguage.zh;
});

final appTextProvider = Provider<Map<String, String>>((ref) {
  final language = ref.watch(languageProvider);
  return appText[language]!;
});

const Map<AppLanguage, Map<String, String>> appText = {
  AppLanguage.zh: {
    'appTitle': '悠遊付',
    'easyWallet': 'Easy Wallet',

    'scanTransfer': '掃碼/轉帳',
    'paymentCode': '付款碼',
    'receive': '收款',
    'topUp': '悠遊卡加值機',

    'friday': '週五+2%',
    'coupons': '悠客券',
    'cardCarrier': '悠遊卡\n載具歸戶',
    'voucher': '優惠券',
    'insurance': '保險專區',
    'finance': '金融理財\n專區',
    'registration': '悠遊卡\n記名',
    'acceptedPlaces': '悠遊付\n使用範圍',

    'qr': 'QR',
    'travelHub': '旅遊中心',
    'splitBill': '分帳',
    'festivals': '節慶活動',
    'laundryHub': '洗衣中心',
    'groceries': '超商購物',

    'studentArea': '學生專區',
    'attendance': '出席確認',
    'secondhandBooks': '二手書交易',
    'forum': '學生論壇',

    'home': '首頁',
    'easyCard': '悠遊卡',
    'rideCode': '乘車碼',
    'me': '我的',
    'more': '其他',

    'bebeHelp': '請問需要什麼幫助？',
    'travelHelp': '需要旅遊規劃協助嗎？',
    'ttsHelp': '需要語音協助嗎？',

    'promoTax': '房屋稅',
    'promoCashback': '滿額最高回饋',
    'news': '每日凌晨0點–2點以及上午5點–7點期間...',

    'additionalFeatures': '新增功能',
    'allUsers': '所有使用者',
    'studentAreaSmall': '學生專區',
    'studentOnlyNote': '需綁定學生證才可使用',
    'bebeSupport': 'Bebe 客服支援',
    'tts': '語音協助 TTS',
    'travelRecommendation': '旅遊推薦',

    'feature': '功能',
    'featureSubtitle': '這是目前可點擊的功能原型頁面。',
    'clickableDemo': '可點擊展示',
    'clickableDemoDesc': '此頁面作為所選功能的展示入口。',
    'studentOnlyTitle': '學生身份限定',
    'studentOnlyDesc': '此功能需完成學生證綁定後才可使用。',
    'ttsDemoTitle': '簡短語音提示',
    'ttsDemoDesc': '範例語音：校車 4 分鐘後抵達。',
    'tourismLoop': '三峽旅遊循環',
    'tourismLoopTitle': '三峽旅遊循環',
    'tourismLoopDesc': 'AI 推薦三峽在地美食、古蹟與登山路線。',
    'openAiPlanner': '開啟 AI 行程規劃',
    'attendanceDesc': '綁定學生證後可確認課堂出席紀錄。',
    'secondhandBooksDesc': '學生身份驗證後才能進行二手書交易。',
    'forumDesc': '類似 Dcard / Threads 的校園討論空間。',

    'aiTitle': 'AI 行程規劃',
    'aiSubtitle': '使用 AI 協助建立你的三峽旅遊行程',
    'whereGo': '你想去哪裡玩？',
    'wherePlaceholder': '例如：三峽老街、祖師廟',
    'whenGo': '你打算什麼時候出發？',
    'whoGo': '誰會和你一起去？',
    'solo': '自己一個人',
    'friends': '朋友',
    'family': '家人',
    'interests': '你對什麼感興趣？',
    'chooseAll': '*可複選',
    'historic': '歷史地標',
    'food': '美食',
    'art': '藝術展覽',
    'hiking': '登山健行',
    'shopping': '購物',
    'mustSee': '必看景點',
    'budget': '你的預估預算是多少？',
    'budgetHint': '例如：5000，只輸入數字',
    'next': '下一步',
    'submit': '送出',
    'resultTitle': '三峽一日 AI 行程',
    'resultSubtitle': '依照你的選擇產生的推薦行程',
    'backHome': '回首頁',
    'bindStudent': '綁定學生證',
    'studentLoginTitle': '學生登入',
    'studentLoginDesc': '綁定北大學生證後，即可使用學生限定功能。',
    'studentBoundTitle': '學生證已綁定',
    'studentBoundDesc': '你現在可以使用學生限定的校園服務。',
    'studentId': '學號',
    'studentName': '姓名',
    'studentEmail': '學校信箱',
    'loginBind': '登入並綁定',
    'logout': '登出',
  },

  AppLanguage.en: {
    'appTitle': 'Easy Wallet',
    'easyWallet': 'Easy Wallet',

    'scanTransfer': 'Scan / Transfer',
    'paymentCode': 'Payment Code',
    'receive': 'Receive',
    'topUp': 'EasyCard Top-up',

    'friday': 'Friday +2%',
    'coupons': 'Coupons',
    'cardCarrier': 'Card\nCarrier',
    'voucher': 'Vouchers',
    'insurance': 'Insurance',
    'finance': 'Finance',
    'registration': 'Card\nRegistration',
    'acceptedPlaces': 'Accepted\nPlaces',

    'qr': 'QR',
    'travelHub': 'Travel Hub',
    'splitBill': 'Split Bill',
    'festivals': 'Festivals',
    'laundryHub': 'Laundry Hub',
    'groceries': 'Groceries',

    'studentArea': 'Student Area',
    'attendance': 'Attendance Checker',
    'secondhandBooks': 'Secondhand Books',
    'forum': 'Student Forum',

    'home': 'Home',
    'easyCard': 'EasyCard',
    'rideCode': 'Ride Code',
    'me': 'Me',
    'more': 'More',

    'bebeHelp': 'How may I help you?',
    'travelHelp': 'Need help with travel plan?',
    'ttsHelp': 'Need TTS assistance?',

    'promoTax': 'House Tax',
    'promoCashback': 'Maximum Cashback',
    'news': 'Daily service maintenance from 00:00–02:00 and 05:00–07:00...',

    'additionalFeatures': 'Additional New Features',
    'allUsers': 'All users',
    'studentAreaSmall': 'Student Area',
    'studentOnlyNote': 'Only accessible after Student ID binding',
    'bebeSupport': 'Bebe Customer Support',
    'tts': 'Text-to-Speech',
    'travelRecommendation': 'Travel Recommendation',

    'feature': 'Feature',
    'featureSubtitle': 'This is a clickable prototype page for the selected module.',
    'clickableDemo': 'Clickable Demo',
    'clickableDemoDesc': 'This page is a working placeholder for the selected module.',
    'studentOnlyTitle': 'Student ID Required',
    'studentOnlyDesc': 'This feature unlocks after Student ID verification.',
    'ttsDemoTitle': 'Concise TTS',
    'ttsDemoDesc': 'Example voice output: Shuttle arrives in 4 minutes.',
    'tourismLoop': 'Sanxia Tourism Loop',
    'tourismLoopTitle': 'Sanxia Tourism Loop',
    'tourismLoopDesc': 'AI recommends local food, heritage sites, and hiking trails.',
    'openAiPlanner': 'Open AI Planner',
    'attendanceDesc': 'Check class attendance after Student ID verification.',
    'secondhandBooksDesc': 'Verified student-to-student textbook trading.',
    'forumDesc': 'A campus discussion space like Dcard / Threads.',

    'aiTitle': 'AI Itinerary',
    'aiSubtitle': 'Plan your Sanxia trip with AI assistance',
    'whereGo': 'Where do you want to go?',
    'wherePlaceholder': 'e.g. Sanxia Old Street, Zushi Temple',
    'whenGo': 'When do you plan to go?',
    'whoGo': 'Who is going with you?',
    'solo': 'Solo',
    'friends': 'Friends',
    'family': 'Family',
    'interests': 'What are you interested in?',
    'chooseAll': '*Choose all that apply',
    'historic': 'Historic Landmarks',
    'food': 'Delicious Foods',
    'art': 'Art Galleries',
    'hiking': 'Hiking',
    'shopping': 'Shopping',
    'mustSee': 'Must-see Attractions',
    'budget': 'What is your estimated budget?',
    'budgetHint': 'e.g. 5000, numbers only',
    'next': 'Next',
    'submit': 'Submit',
    'resultTitle': 'Sanxia One-Day AI Itinerary',
    'resultSubtitle': 'A recommended plan based on your choices',
    'backHome': 'Back Home',
    'bindStudent': 'Bind Student ID',
    'studentLoginTitle': 'Student Login',
    'studentLoginDesc': 'Bind your NTPU Student ID to unlock student-only features.',
    'studentBoundTitle': 'Student ID Bound',
    'studentBoundDesc': 'You can now access student-only campus services.',
    'studentId': 'Student ID',
    'studentName': 'Name',
    'studentEmail': 'School Email',
    'loginBind': 'Login & Bind',
    'logout': 'Logout',
    
  },
};