import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_riverpod/legacy.dart';

enum AppLanguage { zh, en }

final languageProvider = StateProvider<AppLanguage>((ref) {
  return AppLanguage.zh;
});

final appTextProvider = Provider<Map<String, String>>((ref) {
  final language = ref.watch(languageProvider);
  return appText[language]!;
});

const Map<AppLanguage, Map<String, String>> appText = {
  AppLanguage.zh: {
    'appTitle': '悠遊付',
    'easyWallet': 'Easy Wallet',

    'scanTransfer': '掃碼/轉帳',
    'paymentCode': '付款碼',
    'receive': '收款',
    'topUp': '悠遊卡加值機',

    'friday': '週五+2%',
    'coupons': '悠客券',
    'cardCarrier': '悠遊卡\n載具歸戶',
    'voucher': '優惠券',
    'insurance': '保險專區',
    'finance': '金融理財\n專區',
    'registration': '悠遊卡\n記名',
    'acceptedPlaces': '悠遊付\n使用範圍',

    'qr': 'QR',
    'travelHub': '旅遊中心',
    'splitBill': '分帳',
    'festivals': '節慶活動',
    'laundryHub': '洗衣中心',
    'laundryHubDesc': '洗衣倒數、空閒機台、QR 預約與完成提醒。',
    'digitalEasyCard': '客製悠遊卡',
    'digitalEasyCardDesc': '與台灣藝術家及大學合作的虛擬悠遊卡設計收藏。',
    'groceries': '超商購物',

    'studentArea': '學生專區',
    'attendance': '出席確認',
    'secondhandBooks': '二手學生市集',
    'forum': '學生論壇',

    'home': '首頁',
    'easyCard': '悠遊卡',
    'rideCode': '乘車碼',
    'me': '我的',
    'more': '其他',

    'bebeHelp': '請問需要什麼幫助？',
    'travelHelp': '需要旅遊規劃協助嗎？',
    'ttsHelp': '需要語音協助嗎？',

    'promoTax': '房屋稅',
    'promoCashback': '滿額最高回饋',
    'news': '每日凌晨0點–2點以及上午5點–7點期間...',

    'additionalFeatures': '新增功能',
    'allUsers': '所有使用者',
    'studentAreaSmall': '學生專區',
    'studentOnlyNote': '需綁定學生證才可使用',
    'seeAll': '查看全部',
    'bebeSupport': 'Bebe 客服支援',
    'tts': '語音協助 TTS',
    'travelRecommendation': '旅遊推薦',

    'feature': '功能',
    'featureSubtitle': '這是目前可點擊的功能原型頁面。',
    'clickableDemo': '可點擊展示',
    'clickableDemoDesc': '此頁面作為所選功能的展示入口。',
    'studentOnlyTitle': '學生身份限定',
    'studentOnlyDesc': '此功能需完成學生證綁定後才可使用。',
    'ttsDemoTitle': '簡短語音提示',
    'ttsDemoDesc': '範例語音：校車 4 分鐘後抵達。',
    'tourismLoop': '三峽旅遊循環',
    'tourismLoopTitle': '三峽旅遊循環',
    'tourismLoopDesc': 'AI 推薦三峽在地美食、古蹟與登山路線。',
    'openAiPlanner': '開啟 AI 行程規劃',
    'attendanceDesc': '綁定學生證後可確認課堂出席紀錄。',
    'secondhandBooksDesc': '學生身份驗證後可安全交換二手書、衣物、家具與宿舍生活用品。',
    'forumDesc': '類似 Dcard / Threads 的校園討論空間。',

    'aiTitle': 'AI 行程規劃',
    'aiSubtitle': '使用 AI 協助建立你的旅遊行程',
    'whereGo': '你想去哪裡玩？',
    'wherePlaceholder': '例如：三峽老街、祖師廟',
    'useMyLocation': '使用我的位置',
    'viewFullMap': '查看完整地圖',
    'preferences': '偏好設定',
    'bound': '已綁定:',
    'studentEasyCard': '學生悠遊卡',
    'whenGo': '你打算什麼時候出發？',
    'whoGo': '誰會和你一起去？',
    'solo': '自己一個人',
    'friends': '朋友',
    'family': '家人',
    'interests': '你對什麼感興趣？',
    'chooseAll': '*可複選',
    'planTripQuestion': '你希望我們怎麼安排？',
    'maximizeBenefits': '最大化你的優惠',
    'maximizeBenefitsBody': '我們會使用你的學生悠遊卡優惠，包含學生折扣與悠遊卡交通優惠，替你安排最適合的行程。',
    'bestMatchBoundCard': '最符合你綁定卡片的方案',
    'bestMatchBoundCardBody': '使用學生票與悠遊卡轉乘優惠，預估最多可省 NT\$165。',
    'historicLandmarks': '歷史地標',
    'deliciousFoods': '美食',
    'artGalleries': '藝文展覽',
    'mustSeeAttractions': '必看景點',
    'prioritizeDiscounts': '優先使用折扣',
    'useEasyCardTransit': '使用悠遊卡交通',
    'studentOffers': '學生優惠',
    'historic': '歷史地標',
    'food': '美食',
    'art': '藝術展覽',
    'hiking': '登山健行',
    'shopping': '購物',
    'mustSee': '必看景點',
    'budget': '你的預估預算是多少？',
    'budgetHint': '例如：5000，只輸入數字',
    'budgetUnder1k': 'NT\$1,000 以下',
    'budget1k3k': 'NT\$1,000–3,000',
    'budget3k5k': 'NT\$3,000–5,000',
    'budgetOver5k': 'NT\$5,000 以上',
    'generateItinerary': '生成行程',
    'generating': '生成中...',
    'generationError': '行程生成失敗，請再試一次',
    'locationRequired': '請輸入目的地',
    'travelTips': '旅遊小提示',
    'saveItinerary': '儲存行程',
    'next': '下一步',
    'submit': '送出',
    'resultTitle': 'AI 一日行程',
    'resultSubtitle': '依照你的選擇產生的推薦行程',
    'backHome': '回首頁',
    'bindStudent': '綁定學生證',
    'studentLoginTitle': '學生登入',
    'studentLoginDesc': '綁定北大學生證後，即可使用學生限定功能。',
    'studentBoundTitle': '學生證已綁定',
    'studentBoundDesc': '你現在可以使用學生限定的校園服務。',
    'studentId': '學號',
    'studentName': '姓名',
    'studentEmail': '學校信箱',
    'studentPassword': '密碼',
    'loginBind': '登入並綁定',
    'logout': '登出',

    'easyCardTitle': '悠遊卡 EasyCard',
    'adultCard': '普通 Adult',
    'easyCardCompany': '悠遊卡公司',
    'easyCardCorpEn': 'EASYCARD CORP.',
    'useVirtualCard': '使用虛擬卡',
    'chooseCardUsage': '選擇如何使用您的虛擬卡',
    'qrScanner': 'QR Scanner',
    'nfc': 'NFC',

    'scanQrTitle': '掃描 QR 付款',
    'scanQrInstruction': '將 QR 碼對準框框內',
    'simulateDynamic': '模擬動態 QR（含金額）',
    'simulateStatic': '模擬靜態 QR（輸入金額）',
    'flashOn': '開燈',
    'flashOff': '關燈',

    'paymentTitle': '確認付款',
    'merchantLabel': '商家',
    'merchantCategory': '類別',
    'paymentAmount': '付款金額',
    'dynamicQrLocked': '金額由商家設定，不可更改',
    'staticQrEnter': '請輸入付款金額',
    'confirmPay': '確認付款',
    'processing': '處理中...',
    'enterAmount': '輸入金額',
    'twdCurrency': 'NT\$',
    'dynamicQrBadge': '動態 QR',
    'staticQrBadge': '靜態 QR',

    'paymentSuccess': '付款成功',
    'paymentFailed': '付款失敗',
    'paymentSuccessDesc': '您的付款已完成，感謝使用悠遊付！',
    'paymentFailedDesc': '交易遭拒絕，請確認餘額後再試一次。',
    'transactionRef': '交易編號',
    'transactionAmount': '交易金額',
    'transactionMerchant': '商家',
    'transactionTime': '交易時間',
    'backToHome': '回首頁',
    'tryAgain': '再試一次',
    'done': '完成',

    'scanStudentId': '掃描學生證 QR',
    'scanStudentIdTitle': '掃描學生證',
    'scanStudentIdInstruction': '將學生證 QR 碼對準框框',
    'scanStudentIdDesc': '掃描學生證上的 QR 碼以自動填入資料',
    'simulateStudentScan': '模擬掃描學生證',
    'studentMajor': '科系',
    'scanFillHint': 'QR 掃描後將自動填入',
    'orManualEntry': '或手動輸入',
    'scanSuccess': '掃描成功！資料已自動填入。',
    'editCardDesign': '編輯卡片外觀',
  },

  AppLanguage.en: {
    'appTitle': 'Easy Wallet',
    'easyWallet': 'Easy Wallet',

    'scanTransfer': 'Scan / Transfer',
    'paymentCode': 'Payment Code',
    'receive': 'Receive',
    'topUp': 'EasyCard Top-up',

    'friday': 'Friday +2%',
    'coupons': 'Coupons',
    'cardCarrier': 'Card\nCarrier',
    'voucher': 'Vouchers',
    'insurance': 'Insurance',
    'finance': 'Finance',
    'registration': 'Card\nRegistration',
    'acceptedPlaces': 'Accepted\nPlaces',

    'qr': 'QR',
    'travelHub': 'Travel Hub',
    'splitBill': 'Split Bill',
    'festivals': 'Festivals',
    'laundryHub': 'Laundry Hub',
    'laundryHubDesc':
        'Laundry countdown, free machines, QR booking, and completion reminders.',
    'digitalEasyCard': 'Digital EasyCard',
    'digitalEasyCardDesc':
        'Customize your virtual EasyCard with artist and university collections.',
    'groceries': 'Groceries',

    'studentArea': 'Student Area',
    'attendance': 'Attendance Checker',
    'secondhandBooks': 'Student Market',
    'forum': 'Student Forum',

    'home': 'Home',
    'easyCard': 'EasyCard',
    'rideCode': 'Ride Code',
    'me': 'Me',
    'more': 'More',

    'bebeHelp': 'How may I help you?',
    'travelHelp': 'Need help with travel plan?',
    'ttsHelp': 'Need TTS assistance?',

    'promoTax': 'House Tax',
    'promoCashback': 'Maximum Cashback',
    'news': 'Daily service maintenance from 00:00–02:00 and 05:00–07:00...',

    'additionalFeatures': 'Additional New Features',
    'allUsers': 'All users',
    'studentAreaSmall': 'Student Area',
    'studentOnlyNote': 'Only accessible after Student ID binding',
    'seeAll': 'See all',
    'bebeSupport': 'Bebe Customer Support',
    'tts': 'Text-to-Speech',
    'travelRecommendation': 'Travel Recommendation',

    'feature': 'Feature',
    'featureSubtitle':
        'This is a clickable prototype page for the selected module.',
    'clickableDemo': 'Clickable Demo',
    'clickableDemoDesc':
        'This page is a working placeholder for the selected module.',
    'studentOnlyTitle': 'Student ID Required',
    'studentOnlyDesc': 'This feature unlocks after Student ID verification.',
    'ttsDemoTitle': 'Concise TTS',
    'ttsDemoDesc': 'Example voice output: Shuttle arrives in 4 minutes.',
    'tourismLoop': 'Sanxia Tourism Loop',
    'tourismLoopTitle': 'Sanxia Tourism Loop',
    'tourismLoopDesc':
        'AI recommends local food, heritage sites, and hiking trails.',
    'openAiPlanner': 'Open AI Planner',
    'attendanceDesc': 'Check class attendance after Student ID verification.',
    'secondhandBooksDesc':
        'Verified student market for books, clothes, furniture, and dorm-life items.',
    'forumDesc': 'A campus discussion space like Dcard / Threads.',

    'aiTitle': 'AI Itinerary',
    'aiSubtitle': 'Plan your trip with AI assistance',
    'whereGo': 'Where do you want to go?',
    'wherePlaceholder': 'e.g. Sanxia Old Street, Zushi Temple',
    'useMyLocation': 'Use my location',
    'viewFullMap': 'View full map',
    'preferences': 'Preferences',
    'bound': 'Bound:',
    'studentEasyCard': 'Student EasyCard',
    'whenGo': 'When do you plan to go?',
    'whoGo': 'Who is going with you?',
    'solo': 'Solo',
    'friends': 'Friends',
    'family': 'Family',
    'interests': 'What are you interested in?',
    'chooseAll': '*Choose all that apply',
    'planTripQuestion': 'How should we plan your trip?',
    'maximizeBenefits': 'Maximize Your Benefits',
    'maximizeBenefitsBody':
        "We'll use your Student EasyCard benefits including student discounts and EasyCard transit offers to build the best itinerary for you.",
    'bestMatchBoundCard': 'Best match for your bound card',
    'bestMatchBoundCardBody':
        'Estimated total savings up to NT\$165 using student admission offers and EasyCard transit discounts.',
    'historicLandmarks': 'Historic Landmarks',
    'deliciousFoods': 'Delicious Foods',
    'artGalleries': 'Art Galleries',
    'mustSeeAttractions': 'Must-see Attractions',
    'prioritizeDiscounts': 'Prioritize Discounts',
    'useEasyCardTransit': 'Use EasyCard Transit',
    'studentOffers': 'Student Offers',
    'historic': 'Historic Landmarks',
    'food': 'Delicious Foods',
    'art': 'Art Galleries',
    'hiking': 'Hiking',
    'shopping': 'Shopping',
    'mustSee': 'Must-see Attractions',
    'budget': 'What is your estimated budget?',
    'budgetHint': 'e.g. 5000, numbers only',
    'budgetUnder1k': 'Under NT\$1,000',
    'budget1k3k': 'NT\$1,000–3,000',
    'budget3k5k': 'NT\$3,000–5,000',
    'budgetOver5k': 'Over NT\$5,000',
    'generateItinerary': 'Generate Itinerary',
    'generating': 'Generating...',
    'generationError': 'Failed to generate itinerary. Please try again.',
    'locationRequired': 'Please enter a destination',
    'travelTips': 'Travel Tips',
    'saveItinerary': 'Save Itinerary',
    'next': 'Next',
    'submit': 'Submit',
    'resultTitle': 'AI One-Day Itinerary',
    'resultSubtitle': 'A recommended plan based on your choices',
    'backHome': 'Back Home',
    'bindStudent': 'Bind Student ID',
    'studentLoginTitle': 'Student Login',
    'studentLoginDesc':
        'Bind your NTPU Student ID to unlock student-only features.',
    'studentBoundTitle': 'Student ID Bound',
    'studentBoundDesc': 'You can now access student-only campus services.',
    'studentId': 'Student ID',
    'studentName': 'Name',
    'studentEmail': 'School Email',
    'studentPassword': 'Password',
    'loginBind': 'Login & Bind',
    'logout': 'Logout',

    'easyCardTitle': 'Easy Card EasyCard',
    'adultCard': 'General Adult',
    'easyCardCompany': 'EasyCard Corp',
    'easyCardCorpEn': 'EASYCARD CORP.',
    'useVirtualCard': 'Use Virtual Card',
    'chooseCardUsage': 'Choose how to use your virtual card',
    'qrScanner': 'QR Scanner',
    'nfc': 'NFC',

    'scanQrTitle': 'Scan QR to Pay',
    'scanQrInstruction': 'Align the QR code within the frame',
    'simulateDynamic': 'Simulate Dynamic QR (fixed amount)',
    'simulateStatic': 'Simulate Static QR (enter amount)',
    'flashOn': 'Flash On',
    'flashOff': 'Flash Off',

    'paymentTitle': 'Confirm Payment',
    'merchantLabel': 'Merchant',
    'merchantCategory': 'Category',
    'paymentAmount': 'Payment Amount',
    'dynamicQrLocked': 'Amount set by merchant, cannot be changed',
    'staticQrEnter': 'Please enter the payment amount',
    'confirmPay': 'Confirm Payment',
    'processing': 'Processing...',
    'enterAmount': 'Enter Amount',
    'twdCurrency': 'NT\$',
    'dynamicQrBadge': 'Dynamic QR',
    'staticQrBadge': 'Static QR',

    'paymentSuccess': 'Payment Successful',
    'paymentFailed': 'Payment Failed',
    'paymentSuccessDesc':
        'Your payment is complete. Thank you for using Easy Wallet!',
    'paymentFailedDesc':
        'Transaction declined. Please check your balance and try again.',
    'transactionRef': 'Transaction Ref',
    'transactionAmount': 'Amount',
    'transactionMerchant': 'Merchant',
    'transactionTime': 'Time',
    'backToHome': 'Back to Home',
    'tryAgain': 'Try Again',
    'done': 'Done',

    'scanStudentId': 'Scan Student ID QR',
    'scanStudentIdTitle': 'Scan Student ID',
    'scanStudentIdInstruction':
        'Align the student card QR code within the frame',
    'scanStudentIdDesc':
        'Scan the QR code on your student card to auto-fill the form',
    'simulateStudentScan': 'Simulate Student ID Scan',
    'studentMajor': 'Major',
    'scanFillHint': 'QR scan will auto-fill the fields',
    'orManualEntry': 'Or enter manually',
    'scanSuccess': 'Scanned successfully! Fields have been filled in.',
    'editCardDesign': 'Edit Card Design',
  },
};
